rustler::atoms! {
    ok,
    error,
    nil,
    result,

    rust_request_call,

    rust_request_storage_kv_put,
    rust_request_storage_kv_increment,
    rust_request_storage_kv_delete,
    rust_request_storage_kv_clear,

    rust_request_storage_kv_get,
    rust_request_storage_kv_exists,
    rust_request_storage_kv_get_prev,
    rust_request_storage_kv_get_next,

    readonly,
    seed,
    seedf64,
    entry_signer,
    entry_prev_hash,
    entry_slot,
    entry_prev_slot,
    entry_height,
    entry_epoch,
    entry_vr,
    entry_dr,
    tx_signer,
    tx_nonce,
    tx_hash,
    account_origin,
    account_caller,
    account_current,
    call_counter,
    call_exec_points,
    call_exec_points_remaining,
    attached_symbol,
    attached_amount,
}
